# Generated by Django 5.0.3 on 2024-12-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_floors_pre_eq', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], help_text='Number of floors ranging from 1 to 9.', verbose_name='Number of Floors Before Earthquake')),
                ('age_building', models.PositiveSmallIntegerField(help_text='Building age in years (0 to 999).', verbose_name='Building Age')),
                ('plinth_area_sq_ft', models.FloatField(help_text='Plinth area in square feet (70 to 5000).', verbose_name='Plinth Area (sq. ft.)')),
                ('height_ft_pre_eq', models.FloatField(help_text='Building height in feet (6 to 99).', verbose_name='Height Before Earthquake (ft)')),
                ('land_surface_condition', models.CharField(choices=[('Flat', 'Flat'), ('Moderate slope', 'Moderate slope'), ('Steep slope', 'Steep slope')], max_length=20, verbose_name='Land Surface Condition')),
                ('foundation_type', models.CharField(choices=[('Other', 'Other'), ('Mud mortar-Stone/Brick', 'Mud mortar-Stone/Brick'), ('Cement-Stone/Brick', 'Cement-Stone/Brick'), ('RC', 'RC')], max_length=30, verbose_name='Foundation Type')),
                ('roof_type', models.CharField(choices=[('Bamboo/Timber-Light roof', 'Bamboo/Timber-Light roof'), ('Bamboo/Timber-Heavy roof', 'Bamboo/Timber-Heavy roof'), ('RCC/RB/RBC', 'RCC/RB/RBC')], max_length=30, verbose_name='Roof Type')),
                ('ground_floor_type', models.CharField(choices=[('Mud', 'Mud'), ('Brick/Stone', 'Brick/Stone'), ('RC', 'RC'), ('Timber', 'Timber'), ('Other', 'Other')], max_length=20, verbose_name='Ground Floor Type')),
                ('other_floor_type', models.CharField(choices=[('Not applicable', 'Not applicable'), ('TImber/Bamboo-Mud', 'TImber/Bamboo-Mud'), ('Timber-Planck', 'Timber-Planck'), ('RCC/RB/RBC', 'RCC/RB/RBC')], max_length=30, verbose_name='Other Floor Type')),
                ('position', models.CharField(choices=[('Not attached', 'Not attached'), ('Attached-1 side', 'Attached-1 side'), ('Attached-2 side', 'Attached-2 side'), ('Attached-3 side', 'Attached-3 side')], max_length=20, verbose_name='Position')),
                ('plan_configuration', models.CharField(choices=[('Rectangular', 'Rectangular'), ('L-shape', 'L-shape'), ('Square', 'Square'), ('T-shape', 'T-shape'), ('Multi-projected', 'Multi-projected'), ('H-shape', 'H-shape'), ('U-shape', 'U-shape'), ('Others', 'Others'), ('E-shape', 'E-shape'), ('Building with Central Courtyard', 'Building with Central Courtyard')], max_length=50, verbose_name='Plan Configuration')),
                ('technical_solution_proposed', models.CharField(choices=[('Major repair', 'Major repair'), ('Reconstruction', 'Reconstruction'), ('Minor repair', 'Minor repair'), ('No need', 'No need')], max_length=20, verbose_name='Proposed Technical Solution')),
                ('has_superstructure', models.CharField(choices=[('adobe_mud', 'Adobe Mud'), ('mud_mortar_stone', 'Mud Mortar Stone'), ('stone_flag', 'Stone Flag'), ('cement_mortar_stone', 'Cement Mortar Stone'), ('mud_mortar_brick', 'Mud Mortar Brick'), ('cement_mortar_brick', 'Cement Mortar Brick'), ('timber', 'Timber'), ('rc_non_engineered', 'RC Non-Engineered'), ('rc_engineered', 'RC Engineered'), ('other', 'Other')], max_length=30, verbose_name='Has Superstructure')),
                ('address', models.TextField(verbose_name='Address')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
            ],
        ),
    ]
